### ISSUE TITLE
startTime isn't always set for FINISHED executions, endTime not for FAILED

### ISSUE THREAD

**Issue by kba** [infolis/infoLink#25]
c.f. http://infolis.gesis.org/infolink/api/monitor

**Comment by Dommii** [comment]
Should be corrected, please check the pull request.

**Comment by kba** [comment]
The `FINISHED` executions still have no endTime

**Comment by Dommii** [comment]
I only see FINISHED executions with endTime, still an open issue?

**Comment by kba** [comment]
Great.
