### ISSUE TITLE
encoding issue in TextExtractor - when run on server only

### ISSUE THREAD

**Issue by bolandka** [infolis/infoLink#28]
missing chars in converted text files when used on server in conjunction with dset

**Comment by kba** [comment]
Can you give more details? What kinds of chars are missing? What's are the `LC_*` settings of the shell? Do you have examples to test with?

**Comment by bolandka** [comment]
see here for an example, a link to the pdf file is included (you can also find the corresponding files on the server at datasets/ssoar/subsets/all): https://gist.github.com/bolandka/c7d0364c7b8675b3e190 encoding is set to "en_US.UTF-8" both on the server and on the local machine.

**Comment by kba** [comment]
I see, all the umlauts are replaced by question marks. We'll need to go through the CLI and check the InputStreams/Outputstreams. Thanks for investigating.

**Comment by kba** [comment]
Was this fixed?

**Comment by bolandka** [comment]
Yes, that's why I closed it. Not sure what caused or fixed it. I set the standard java file encoding on the server to utf8 and restarted the dset text extraction with the current infoLink build.

**Comment by bolandka** [comment]
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

setting the file encoding to utf8 is what does the trick
