### ISSUE TITLE
Context size

### ISSUE THREAD

**Issue by Dommii** [infolis/infoLink#5]
Why is the context size always 5 (on both sides) and cannot be less?

**Comment by bolandka** [comment]
a context is now a whole sentence (https://github.com/infolis/infoLink/commit/c4a5dfabbbdd5d5d131fbc05e4a93bd163f08de9, https://github.com/infolis/infoLink/commit/0da9782ca7f8a7cdb39d8e2b1cf81283fd0533c9)

number of words used for constructing patterns can be adjusted and is independent of context size (https://github.com/infolis/infoLink/commit/d3d507da8c55610b33bf6c9926773109f95296af)
