### ISSUE TITLE
NullPointerException when trying to retrieve reliability of QueryService

### ISSUE THREAD

**Issue by bolandka** [infolis/infoLink#53]
...in Resolver. Observed for DaraHTMLQueryService on local execution. Using the reliability is thus inhibited for now, but should be fixed and included again.

**Comment by kba** [comment]
Can someone provide a reproducible JSON to fix this? @Dommii  @bolandka

**Comment by bolandka** [comment]
The error does not occur right now because we removed the problematic part in commit https://github.com/infolis/infoLink/commit/f8dce5729eb4c8d3464b319c7c674575793de50a. Will investigate it locally, the error occurred during local execution of a test so it's not related to the webservice (and thus, there is no json file to reproduce it). If the webservice was deployed after the above mentioned commit and issue #57 created after that, these two issues are not related.

**Comment by bolandka** [comment]
Reason: when using the setQueryServiceClasses variant (instead of setQueryServices), QueryService will not be posted and thus does not have a uri. Later, its uri is assigned to a SearchResult

``` js
sr.setQueryService(this.getUri());
```

(in HTMLQueryService)

in SolrQueryService, the QueryService seems not to be set at all for generated search results.

Thus, when the service shall later be resolved and its reliability retrieved, an NPE is thrown. 

Add this to ResolverTest to check after fixing:

```
QueryService qs = new HTMLQueryService("http://www.da-ra.de/dara/study/web_search_show",0.5);

public ResolverTest() {
    dataStoreClient.post(QueryService.class, qs);
}
```

and in every test for each search result:

```
<SearchResultInstance>.setQueryService(qs.getUri());
```

**Comment by Dommii** [comment]
The TextualReference did not store the mentionsEntity. Within the Resolver, the entity of the TextualReference is requested to create the EntityLink. Added it in the code and in the DM.

**Comment by bolandka** [comment]
merged
