### ISSUE TITLE
OutOfMemoryError: increased memory usage / memory leak?

### ISSUE THREAD

**Issue by bolandka** [infolis/infoLink#66]
all tests pass, but:
_recently_, when running the whole Bootstrapping procedure from the CLI, java runs out of heap space. With the same corpus, CLI paramers and json file as _before_ when there was no problem. 
_recently_: tested today.
_before_: Sat Nov 21 12:22:27 CET 2015. Maybe it still worked some time after that, that was the last time I checked before today. Unfortunately, I don't know when exactly this started to occur. 

So many commits in between... Any ideas where I should start looking?

**Comment by bolandka** [comment]
Update: its the passing on of the logs introduced here https://github.com/infolis/infoLink/commit/c6ca358183c8dc3baa5c47749c4454ffdf7d691b:

```
subExec.setLog(getLog());
```

Guess we'll have to come up with a different solution for this on the long run.
But for now, it's an easy one to fix :) On the cost of not having the most helpful logs... But for now, I prefer working executions to good logs of them failing ;)
Adding a fix in a minute...

**Comment by kba** [comment]
Thank you, yeah, that's what I feared. They get rather insanely huge these logs.

**Comment by bolandka** [comment]
"fixed" it: simply removed the above cited inheritance for now. Created a separate issue for the logging. I did not touch the subExecution-structure as I think it might still prove useful used in a different way.
