### ISSUE TITLE
How to reliably restart Tomcat?

### ISSUE THREAD

**Issue by kba** [infolis/infoLink#69]
We have a problem with PermGen OutOfMemory errors due to a bug in the currently deployed version of Jersey.

For now, redeploying the WAR causes Tomcat to eventually and gracelessly refuse to work: The backend doesn't crash, it just clogs the port.

Even in a better mood, Tomcat doesn't always react to a quit signal on its termination port. 

And Tomcat likes Tomcat so Tomcat starts a Tomcat now and then. In the end, someone has to kill nine all those processes because SIGTERM doesn't do it.

Has anyone a good recommendation or an idea on the correct setup? How can we make sure, Tomcat really crashes and doesn't hang and is restarted once that happens? I'm doing that for the frontend with supervisor and nodemon (also tried forever) which are node tools but quite flexible.

Any ideas @Dommii @bolandka ?

**Comment by bolandka** [comment]
None currently, I'm afraid :( Will do some research on that

**Comment by stweil** [comment]
Would assigning more memory reduce the frequency of the problem? Could an automated daily restart then be a solution (maybe with kill -KILL)?

**Comment by kba** [comment]
The problem is that it's not a memory leak per se but has to do with how Jersey doesn't properly release the classes of an application when it is undeployed. 

I did that in the past, just restarting Tomcat regularly, but it's not really a solution, it cannot be the standard way and there's too many possibilities something can go wrong.

But, we'll upgrade our dependencies soon enough so hopefully this will solve itself with the upstream bugfixes.

**Comment by kba** [comment]
I've revamped infolis-datasets to control a folder-local Tomcat instance with `make` and unix tools to find the right pid and kill it. Not perfect, but much better.

@Dommii Could the hanging process be due to a daemon/non-daemon thread? Does the threadPool setting of tomcat (c.f. https://github.com/infolis/infolis-datasets/blob/master/conf/server.xml) help us there?

**Comment by kba** [comment]
We've moved to docker.
